//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oldhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public long id { get; set; }
        public string BookingType { get; set; }
        public string PackageName { get; set; }
        public string PackageDetails { get; set; }
        public string Duration { get; set; }
        public string Price { get; set; }
        public string Installment { get; set; }
        public Nullable<long> regid { get; set; }
    
        public virtual Register Register { get; set; }
        public virtual Package Packages1 { get; set; }
        public virtual Package Package1 { get; set; }
    }
}
