//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oldhouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requested
    {
        public long id { get; set; }
        public string Request { get; set; }
        public string Accept { get; set; }
        public string Reject { get; set; }
    }
}
